# Generated by Django 4.1.7 on 2024-02-01 16:19

import datetime
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=100)),
                ('is_on', models.BooleanField()),
                ('description', models.CharField(max_length=100)),
                ('label', models.CharField(default='', max_length=100)),
                ('markup', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=None)),
            ],
        ),
        migrations.CreateModel(
            name='EventType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Intruder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MainEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media', models.CharField(max_length=100)),
                ('time', models.DateTimeField(default=datetime.datetime(2024, 2, 1, 19, 19, 45, 814234))),
                ('is_reviewed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boulding_box', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=None)),
                ('is_confirmed', models.BooleanField(default=True)),
                ('camera_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.camera')),
                ('event_type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.eventtype')),
                ('intruder_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.intruder')),
                ('main_event_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.mainevent')),
            ],
        ),
    ]
