# Generated by Django 4.1.7 on 2024-02-09 09:51

import datetime
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountPeople',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(default=datetime.datetime(2024, 2, 9, 12, 51, 36, 701833))),
                ('list_media', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default='', max_length=100), default=list, size=None)),
                ('people', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='mainevent',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 9, 12, 51, 36, 700949)),
        ),
    ]
